jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: docker build -t manifoldsite . 
    name: Build docker image with a default name
  - bash: docker tag manifoldsite $(dockerId).azurecr.io/latest:$(imageName)
    name: Retag docker image 

- job: Authenticate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
    name: Authenticate ACR
  dependsOn: Build
  condition: succeeded()

- job: Push
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: docker push $(dockerId).azurecr.io/latest:$(imageName)
    name: Push built docker image into ACR
  dependsOn: Login 
  condition: succeeded()

# steps:
# - bash: |
#    # Write your commands here
#    # Use the environment variables input below to pass secret variables to this script
#    docker build -t manifoldsite . # include other options to meet your needs
#    docker tag manifoldsite $(dockerId).azurecr.io/latest:$(Build.SourceVersion) 
# - bash: |
#    docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
#    docker push $(dockerId).azurecr.io/latest:$(Build.SourceVersion) 

# - task: PublishTestResults@2
#   inputs:
#     testRunner: VSTest
#     testResultsFiles: '**/*.trx'