jobs:
- job: Build
  displayName: 'Build and Push'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      inlineScript: |
        #!/bin/bash
        docker build -t manifoldsite . 
        docker tag manifoldsite $(dockerId).azurecr.io/latest:$(Build.SourceVersion)

  - task: Docker@1
      displayName: 'Register to ACR'
      inputs:
        inlineScript: |
          #!/bin/bash
          docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io

  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      inlineScript: |
        #!/bin/bash
         docker push $(dockerId).azurecr.io/latest:$(Build.SourceVersion)