# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: Dockerize@0
  script: docker build -t $(dockerId)/$(imageName)

- task: LoginToAzure@2
  script: docker login -u $(dockerId) -p $(dockerPassword) manifoldsite.azurecr.io

  - task: PushToCR@2
    script: |
    docker login -u $(dockerId).azurecr.io -p $(pswd) $(dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-RESULTS.xml'
    testRunTitle: 'Test results for JavaScript'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
