# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts


jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    buildConfiguration: 'Release'
    imageName: Build.SourceVersion
  steps:
  - bash: docker build -t manifoldsite . 
  - bash: docker tag manifoldsite $(dockerId).azurecr.io/latest:$(Build.SourceVersion) 
  #displayName: 'Build docker image'

- job: Push
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    buildConfiguration: 'Release'
    imageName: Build.SourceVersion
  #steps:
#  - bash: |
#    docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
#    docker push $(dockerId).azurecr.io/latest:$(Build.SourceVersion) 
#   displayName: 'Push built docker image to container registry'
  dependsOn: Build
  condition: succeeded()

# steps:
# - bash: |
#    # Write your commands here
#    # Use the environment variables input below to pass secret variables to this script
#    docker build -t manifoldsite . # include other options to meet your needs
#    docker tag manifoldsite $(dockerId).azurecr.io/latest:$(Build.SourceVersion) 
# - bash: |
#    docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
#    docker push $(dockerId).azurecr.io/latest:$(Build.SourceVersion) 

# - task: PublishTestResults@2
#   inputs:
#     testRunner: VSTest
#     testResultsFiles: '**/*.trx'