# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'
  imageName: '(Build.SourceVersion)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    docker build --tag 'pepe' . #$(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)




- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'