jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: docker build --target $(targetName) -t manifoldsite . 
    displayName: 'Build docker image'
  - bash: docker tag manifoldsite $(dockerId).azurecr.io/latest:$(Build.SourceVersion)
    name: 'Retag_docker_image'
  - bash: docker login -u $(dockerId) -p $(dockerPassword) $(dockerid).azurecr.io
    name: 'Authenticate_ACR'
  - bash: docker push $(dockerId).azurecr.io/latest:$(Build.SourceVersion)
    name: 'Push_docker_image' 
